name: 构建并部署到 Github Pages

on:
  # Runs on pushes targeting the default branch
  push:
      branches: ['master']
permissions:
    contents: write
jobs:
  build-and-deploy:
    name: Ubuntu 构建和推送
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    env:
      STORE_PATH: ''
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: '9.1.2'

      - name: 获取 pnpm store 目录
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: 配置 pnpm 缓存
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建
        run: pnpm docs:build

      - name: 推送到 gh-pages 分支
        uses: JamesIves/github-pages-deploy-action@v4
        timeout-minutes: 10
        with:
          token: ${{ GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .vitepress/dist
          CLEAN: true


